### ISSUE TITLE
sshfs formula broken with non-standard prefix

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew-fuse#62]
I install homebrew to `/Homebrew`.

I did `brew cask install --force osxfuse` to ensure I'm upgraded on the lower-level libraries.

The build error is as follows:

```
★ brew upgrade
 ↩ Mon Aug 29 14:41:43 PDT 2016
==> Upgrading 1 outdated package, with result:
homebrew/fuse/sshfs 2.8
==> Upgrading homebrew/fuse/sshfs
==> Downloading https://github.com/libfuse/sshfs/releases/download/sshfs_2.8/ssh
Already downloaded: /Users/glyph/Library/Caches/Homebrew/sshfs-2.8.tar.gz
==> Downloading https://github.com/libfuse/sshfs/commit/e5acfce8eda218d.patch
Already downloaded: /Users/glyph/Library/Caches/Homebrew/sshfs--patch-53b165353c944303d0839bbe1bf16c04eaaee2deca89ccff729b1974d14aa8cb.patch
==> Patching
==> Applying e5acfce8eda218d.patch
patching file sshfs.c
==> ./configure --prefix=/Homebrew/Cellar/sshfs/2.8
==> make install
Last 15 lines from /Users/glyph/Library/Logs/Homebrew/sshfs/02.make:
2016-08-29 14:41:47 -0700

make
install

clang -DHAVE_CONFIG_H -I.  -D_REENTRANT -DFUSE_USE_VERSION=26 -DLIBDIR=\"/Homebrew/Cellar/sshfs/2.8/lib\" -DIDMAP_DEFAULT="\"user\""  -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -D_REENTRANT -I/usr/local/include/osxfuse/fuse -I/Homebrew/Cellar/pcre/8.39/include -I/Homebrew/Cellar/glib/2.48.1/include/glib-2.0 -I/Homebrew/Cellar/glib/2.48.1/lib/glib-2.0/include -I/Homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat -c -o sshfs-sshfs.o `test -f 'sshfs.c' || echo './'`sshfs.c
clang -DHAVE_CONFIG_H -I.  -D_REENTRANT -DFUSE_USE_VERSION=26 -DLIBDIR=\"/Homebrew/Cellar/sshfs/2.8/lib\" -DIDMAP_DEFAULT="\"user\""  -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -D_REENTRANT -I/usr/local/include/osxfuse/fuse -I/Homebrew/Cellar/pcre/8.39/include -I/Homebrew/Cellar/glib/2.48.1/include/glib-2.0 -I/Homebrew/Cellar/glib/2.48.1/lib/glib-2.0/include -I/Homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat -c -o sshfs-cache.o `test -f 'cache.c' || echo './'`cache.c
clang -DHAVE_CONFIG_H -I.  -D_REENTRANT -DFUSE_USE_VERSION=26 -DLIBDIR=\"/Homebrew/Cellar/sshfs/2.8/lib\" -DIDMAP_DEFAULT="\"user\""  -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -D_REENTRANT -I/usr/local/include/osxfuse/fuse -I/Homebrew/Cellar/pcre/8.39/include -I/Homebrew/Cellar/glib/2.48.1/include/glib-2.0 -I/Homebrew/Cellar/glib/2.48.1/lib/glib-2.0/include -I/Homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat -c -o compat/sshfs-darwin_compat.o `test -f 'compat/darwin_compat.c' || echo './'`compat/darwin_compat.c
clang -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -D_REENTRANT -I/usr/local/include/osxfuse/fuse -I/Homebrew/Cellar/pcre/8.39/include -I/Homebrew/Cellar/glib/2.48.1/include/glib-2.0 -I/Homebrew/Cellar/glib/2.48.1/lib/glib-2.0/include -I/Homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat   -o sshfs sshfs-sshfs.o sshfs-cache.o  compat/sshfs-darwin_compat.o -L/usr/local/lib -L/Homebrew/Cellar/glib/2.48.1/lib -L/Homebrew/opt/gettext/lib -losxfuse -pthread -liconv -lgthread-2.0 -lglib-2.0 -lintl 
ld: library not found for -losxfuse
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sshfs] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-fuse/issues


 ↪ Mon Aug 29 14:41:51 PDT 2016 (★ brew upgrade) (8 seconds elapsed)
glyph@elfa:~  ERROR:1  gary:🐻  
★ 
```

**Comment by glyph** [comment]
Dropping into a debug shell with `brew upgrade -vvvv debug`, I discovered that running `make` in that shell resulted in the same error, but running the last command in the shell (`clang -D_FILE_OFFSET_BITS=64 -D_DARWIN_USE_64_BIT_INODE -D_REENTRANT -I/usr/local/include/osxfuse/fuse -I/Homebrew/Cellar/pcre/8.39/include -I/Homebrew/Cellar/glib/2.48.1/include/glib-2.0 -I/Homebrew/Cellar/glib/2.48.1/lib/glib-2.0/include -I/Homebrew/opt/gettext/include -g -O2 -Wall -W -I./compat   -o sshfs sshfs-sshfs.o sshfs-cache.o  compat/sshfs-darwin_compat.o -L/usr/local/lib -L/Homebrew/Cellar/glib/2.48.1/lib -L/Homebrew/opt/gettext/lib -losxfuse -pthread -liconv -lgthread-2.0 -lglib-2.0 -lintl `) resulted in only a warning (`clang: warning: argument unused during compilation: '-pthread'`) and produced a functioning `sshfs` binary.

**Comment by glyph** [comment]
The differences between the shell environment and the `make` environment are as follows: 

```diff
bash-3.2$ diff -u shell.env makefile.env 
--- shell.env	2016-08-29 14:35:15.000000000 -0700
+++ makefile.env	2016-08-29 14:35:35.000000000 -0700
@@ -1,7 +1,7 @@
 ACLOCAL_PATH=/Homebrew/opt/gettext/share/aclocal:/Homebrew/share/aclocal
 Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.N39kbrVdOx/Render
 CARINA_USERNAME=glyph
-CC=clang
+CC=env | sort > makefile.env ; echo --
 CLICOLOR=1
 CMAKE_INCLUDE_PATH=/usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
 CMAKE_LIBRARY_PATH=/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
@@ -22,7 +22,7 @@
 HOMEBREW_BREW_FILE=/Homebrew/bin/brew
 HOMEBREW_CACHE=/Users/glyph/Library/Caches/Homebrew
 HOMEBREW_CC=clang
-HOMEBREW_CCCFG=sa
+HOMEBREW_CCCFG=Osa
 HOMEBREW_CELLAR=/Homebrew/Cellar
 HOMEBREW_CURL=/usr/bin/curl
 HOMEBREW_CXX=clang++
@@ -56,13 +56,15 @@
 LOGNAME=glyph
 M4=/usr/bin/m4
 MACOSX_DEPLOYMENT_TARGET=10.11
-MAKEFLAGS=-j8
+MAKEFLAGS= --jobserver-fds=3,4 -j
+MAKELEVEL=2
+MFLAGS=- --jobserver-fds=3,4 -j
 OBJC=clang
 OBJCXX=clang++
 PATH=/Homebrew/Library/Homebrew/shims/super:/Homebrew/opt/pkg-config/bin:/Homebrew/opt/autoconf/bin:/Homebrew/opt/automake/bin:/Homebrew/opt/libtool/bin:/Homebrew/opt/gettext/bin:/Homebrew/opt/pcre/bin:/Homebrew/opt/glib/bin:/usr/bin:/bin:/usr/sbin:/sbin
 PIP_INDEX_URL=http://127.0.0.1:3141/root/pypi/+simple/
 PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.11
-PKG_CONFIG_PATH=/Homebrew/opt/libffi/lib/pkgconfig:/Homebrew/opt/pcre/lib/pkgconfig:/Homebrew/opt/glib/lib/pkgconfig:/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse
+PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/Homebrew/opt/libffi/lib/pkgconfig:/Homebrew/opt/pcre/lib/pkgconfig:/Homebrew/opt/glib/lib/pkgconfig:/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse
 PWD=/private/tmp/sshfs-20160829-4599-sp1tbj/sshfs-2.8
 PYTHONSTARTUP=/Users/glyph/Settings/Python/prompt.py
 RBENV_SHELL=bash
@@ -71,7 +73,7 @@
 SCREEN_TAB_INACTIVE= wr
 SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
 SHELL=/bin/bash
-SHLVL=2
+SHLVL=3
 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.iN9elF8WqN/Listeners
 TEMP=/tmp
 TERM=xterm-256color
```

**Comment by glyph** [comment]
The offending variable appears to be `HOMEBREW_CCCFG=Osa`; if I set only that, the shell command fails.

**Comment by glyph** [comment]
Even stranger, if I manually cause the binary to be built, and then exit the debug shell and select "ignore", I get:

```
Choose an action: 2
ln -s ../Cellar/sshfs/2.5.0/bin/sshfs sshfs
ln -s ../../../Cellar/sshfs/2.5.0/share/man/man1/sshfs.1 sshfs.1
Error: Empty installation
/Homebrew/Library/Homebrew/formula_installer.rb:614:in `build'
/Homebrew/Library/Homebrew/formula_installer.rb:246:in `install'
/Homebrew/Library/Homebrew/cmd/upgrade.rb:97:in `upgrade_formula'
/Homebrew/Library/Homebrew/cmd/upgrade.rb:67:in `block in upgrade'
/Homebrew/Library/Homebrew/cmd/upgrade.rb:66:in `each'
/Homebrew/Library/Homebrew/cmd/upgrade.rb:66:in `upgrade'
/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

and it rolls back the upgrade.

**Comment by glyph** [comment]
brew version info:

```
Homebrew 0.9.9 (git revision 8e29cf; last commit 2016-08-28)
Homebrew/homebrew-core (git revision 17276; last commit 2016-08-29)
```

**Comment by tdsmith** [comment]
If you look at the logs in ~/Library/Logs/Homebrew, the `.cc` logs will show any superenv modifications to compiler/linker invocations. `brew gist-logs sshfs` will post the logs and some other debugging information and give you a URL to share.

**Comment by glyph** [comment]
@tdsmith here you go: https://gist.github.com/7699f9972cd51306a22578aa553c46c9

**Comment by tdsmith** [comment]
My questions today are: a) Why is superenv editing -L/usr/local/lib out of the clang invocation at https://gist.github.com/anonymous/7699f9972cd51306a22578aa553c46c9#file-02-make-cc-L17 but not during configure? (Something about refurbish_args being triggered?)

b) Is clang having trouble finding /usr/local/lib without having it manually specified, and, if yes,
b1) How come??

**Comment by glyph** [comment]
@tdsmith if I can provide any clues as to why this might be happening, please let me know; I'm happy to do any additional diagnostics.  It's really annoying that I can't update :)

**Comment by Yann-R** [comment]
I encounter exactly the same failure and final error message from the formula
(and I confirm that I use a non standard homebrew prefix, not ``/usr/local``).

Nevertheless I'm quite puzzled by this final message itself:
as visible in the first message, the linker says it can't find the library osxfuse: 
``ld: library not found for -losxfuse``
whilst
- the invoked command uses ``-L/usr/local/lib``
- my dependency to osxfuse is provided by homebrew-cask, that install the official package in ``/usr/local/*``
- and therefore ``/usr/local/lib`` really contains ``libosxfuse``...

**Comment by tdsmith** [comment]
> - the invoked command uses `-L/usr/local/lib`

It secretly doesn't; it's being removed by superenv. But it still ought to be in the linker's search path :(

**Comment by tdsmith** [comment]
Aha, but it's not. Compare:

```
tim@rocketman:Documents$ clang -Xlinker -v
...
Library search paths:
	/usr/lib
	/usr/local/lib
...
```

```
tim@rocketman:Documents$ SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk clang -Xlinker -v
...
Library search paths:
	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib
```

So this is a superenv bug.

**Comment by tdsmith** [comment]
cf https://github.com/Homebrew/brew/issues/844

**Comment by tdsmith** [comment]
I expect this is fixed by https://github.com/Homebrew/brew/pull/845 if you want to test.

**Comment by glyph** [comment]
Looks like... yes?

```console
$ brew update
Updated Homebrew from 8f068fd to 8524893.
No changes to formulae.
$ brew upgrade
==> Upgrading 1 outdated package, with result:
homebrew/fuse/sshfs 2.8
==> Upgrading homebrew/fuse/sshfs
==> Downloading https://github.com/libfuse/sshfs/releases/download/sshfs_2.8/ssh
Already downloaded: /Users/glyph/Library/Caches/Homebrew/sshfs-2.8.tar.gz
==> Downloading https://github.com/libfuse/sshfs/commit/e5acfce8eda218d.patch
Already downloaded: /Users/glyph/Library/Caches/Homebrew/sshfs--patch-53b165353c944303d0839bbe1bf16c04eaaee2deca89ccff729b1974d14aa8cb.patch
==> Patching
==> Applying e5acfce8eda218d.patch
patching file sshfs.c
==> ./configure --prefix=/Homebrew/Cellar/sshfs/2.8
==> make install
🍺  /Homebrew/Cellar/sshfs/2.8: 6 files, 104.5K, built in 3 seconds
```

**Comment by tdsmith** [comment]
I'm not totally sure tbh. There's discussion of `update` behavior in https://github.com/Homebrew/brew/issues/737; the behavior is different and I think more predictable for git users if you set `HOMEBREW_DEVELOPER=1`.
