### ISSUE TITLE
Building fails on 10.11.6

### ISSUE THREAD

**Issue by majes-github** [Homebrew/homebrew-fuse#70]
Output:

```
$ brew install homebrew/fuse/encfs
==> Installing encfs from homebrew/fuse
==> Using the sandbox
==> Downloading https://github.com/vgough/encfs/archive/v1.9.tar.gz
Already downloaded: /Users/mj/Library/Caches/Homebrew/encfs-1.9.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/encfs/1.9 -DCMAKE_BUILD_TYPE=Release -
==> make install
Last 15 lines from /Users/mj/Library/Logs/Homebrew/encfs/02.make:
/tmp/encfs-20160922-29248-1llntz5/encfs-1.9/encfs/main.cpp:579:23: error: assigning to 'int (*)(const char *, const char *, const char *, size_t, int)' (aka 'int (*)(const char *, const char *, const char *, unsigned long, int)') from incompatible type 'int (const char *, const char *, const char *, size_t, int, uint32_t)' (aka 'int (const char *, const char *, const char *, unsigned long, int, unsigned int)'): different number of parameters (5 vs 6)
  encfs_oper.setxattr = encfs_setxattr;
                      ^ ~~~~~~~~~~~~~~
/tmp/encfs-20160922-29248-1llntz5/encfs-1.9/encfs/main.cpp:580:23: error: assigning to 'int (*)(const char *, const char *, char *, size_t)' (aka 'int (*)(const char *, const char *, char *, unsigned long)') from incompatible type 'int (const char *, const char *, char *, size_t, uint32_t)' (aka 'int (const char *, const char *, char *, unsigned long, unsigned int)'): different number of parameters (4 vs 5)
  encfs_oper.getxattr = encfs_getxattr;
                      ^ ~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/encfs-bin.dir/encfs/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/encfs-bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX executable checkops
/usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/checkops.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -lintl CMakeFiles/checkops.dir/encfs/test.cpp.o  -o checkops  -L/tmp/encfs-20160922-29248-1llntz5/encfs-1.9/build/internal/tinyxml2-3.0.0  libencfs.a /usr/local/lib/libosxfuse.dylib /usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libcrypto.dylib internal/tinyxml2-3.0.0/libtinyxml2.a -Wl,-rpath,/tmp/encfs-20160922-29248-1llntz5/encfs-1.9/build/internal/tinyxml2-3.0.0
[ 94%] Built target checkops
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-fuse/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:206:in `raise_api_error': GitHub { (GitHub::AuthenticationFailedError)
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
    from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:174:in `open'
    from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:223:in `issues_matching'
    from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:256:in `issues_for_formula'
    from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:312:in `fetch_issues'
    from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:308:in `issues'
    from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:353:in `dump'
    from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
    from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by umireon** [comment]
It is possible that your installation of FUSE is too old or broken.
You can ensure to the appropriate version of FUSE by running `brew cask reinstall osxfuse`.

**Comment by MikeMcQuaid** [comment]
> You can ensure to the appropriate version of FUSE by running brew cask reinstall osxfuse.

Assuming this fixes it.
